[package]
name = "idotool"
version = "0.1.0"
edition = "2024"

[dependencies]
flate2 = "1.0"
encoding_rs = "0.8"
memmap2 = "0.9"                                      # Optional, for faster file reading
clap = { version = "4.5.53", features = ["derive"] }
hex = "0.4"
